FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn global add ts-node
RUN yarn install

COPY ./src ./src
COPY tsconfig.json nodemon.json tsoa.json ./

CMD ["yarn", "run", "dev"]
