name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Set environment variables
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Build project
        run: yarn build

      - name: Add SSH key and start SSH agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          if [ $? -ne 0 ]; then
            echo "Error adding SSH key"
            exit 1
          fi
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          if [ $? -ne 0 ]; then
            echo "Error adding known host"
            exit 1
          fi
          ssh-add -l
          if [ $? -ne 0 ]; then
            echo "Error listing SSH keys"
            exit 1
          fi
          echo "SSH setup completed successfully"

      - name: Debug SSH key setup
        run: |
          echo "Debugging SSH key setup"
          ssh-add -l || echo "SSH key not found"
          echo "Known hosts:"
          cat ~/.ssh/known_hosts || echo "No known hosts found"
          echo "SSH agent status:"
          ps aux | grep ssh-agent || echo "SSH agent not running"
          exit 1  # Force exit to see the debug output

      - name: Deploy to EC2
        if: always() # This will run even if the previous step fails
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Start deployment at $(date)"
            cd /home/ubuntu/Project-backend-NodeJS  # Updated path
            echo "Pulling latest code"
            git pull origin main
            echo "Installing dependencies"
            yarn install
            echo "Building project"
            yarn build
            echo "Restarting PM2 processes"
            if pm2 describe all | grep -q 'status\s*online'; then
              pm2 restart all
            else
              pm2 start src/server.ts --name "my-app" --interpreter ./node_modules/.bin/ts-node
            fi
            echo "Deployment completed at $(date)"
