name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: yarn install

      - name: Set up environment variables
        run: |
          mkdir -p src/configs
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > src/configs/.env.production
          echo "PORT=${{ secrets.PORT }}" >> src/configs/.env.production
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          PORT: ${{ secrets.PORT }}

      - name: Build the project
        run: yarn build
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          PORT: ${{ secrets.PORT }}

      - name: Run tests
        run: yarn test
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          PORT: ${{ secrets.PORT }}

      # - name: Start the application
      #   run: yarn start
      #   env:
      #     MONGODB_URL: ${{ secrets.MONGODB_URL }}
      #     PORT: ${{ secrets.PORT }}
